name: Dev Image

on:
  push:
    branches:
    - main
    - release-*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.0.0
      with:
        driver-opts: image=moby/buildkit:master
    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push go ghcr
      uses: docker/build-push-action@v3
      with:
        push: true
        platforms: |
          linux/amd64
          linux/arm64
        file: Dockerfile
        tags: ghcr.io/${{ github.repository }}:dev